name: 'gptme-bot'
description: 'A composite action for the gptme-bot workflow using the github_bot.py script'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: false
  anthropic_api_key:
    description: 'Anthropic API Key'
    required: false
  model:
    description: 'Model to use'
    required: false
    default: 'anthropic/claude-sonnet-4-20250514'
  github_token:
    description: 'GitHub Token'
    required: true
  allowlist:
    description: 'Comma-separated list of GitHub usernames allowed to trigger the bot'
    required: true
    default: 'ErikBjare'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install gptme
      shell: bash
      run: |
        pip install gptme[server]

    - name: Write gptme config
      shell: bash
      run: |
        mkdir -p ~/.config/gptme
        cat > ~/.config/gptme/config.toml << EOF
        [prompt]
        about_user = "The user is talking to the gptme bot through GitHub comments. They have initiated conversation by pinging it with @gptme, triggering a GitHub Action in which gptme now runs."
        response_preference = "Don't explain basic concepts"
        EOF

    - name: Run GitHub Bot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        MODEL: ${{ inputs.model }}
        ALLOWLIST: ${{ inputs.allowlist }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        # Download github_bot.py from gptme repo (enables use as reusable action)
        # Pin to specific commit for supply chain security (ba3c0233)
        SCRIPT_URL="https://raw.githubusercontent.com/gptme/gptme/ba3c0233f5f047ef210c732fb59d0c52b9bdd9e5/scripts/github_bot.py"
        curl -fsL "$SCRIPT_URL" > /tmp/github_bot.py
        python /tmp/github_bot.py

    - name: Report error
      if: failure()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        MESSAGE="I'm sorry, I could not fulfill your request. Please check the [log of this run]($RUN_URL) for more information."
        echo "$MESSAGE" | gh issue comment ${{ github.event.issue.number }} -R ${{ github.repository }} --body-file=-
